data:
  task_name: task_1_bed_cat_dog
# trainer:
#   logger:
#     class_path: lightning.pytorch.loggers.TensorBoardLogger
#     init_args:
#       save_dir: lightning_logs/
#       name: task_1_bed_cat_dog