#! /bin/bash

# download data

curl -X GET \
https://Hugging Face.co/datasets/fact-40/pcbm-coco-stuff/resolve/main/data/data.zip?download=true |  grep -Eo "(http|https)://.*" | xargs curl --output artifacts/data/COCO_STUFF.zip

# extract data

unzip artifacts/data/COCO_STUFF.zip -d artifacts/data/COCO_STUFF
