#! /bin/bash

# download data

curl -X GET \
https://Hugging Face.co/datasets/fact-40/pcbm-siim-isic/resolve/main/data/data.zip?download=true |  grep -Eo "(http|https)://.*" | xargs curl --output artifacts/data/SIIM_ISIC.zip

# extract data

unzip artifacts/data/SIIM_ISIC.zip -d artifacts/data/SIIM_ISIC
