#!/usr/bin/env python
import gdown
import zipfile

# download data

url = 'https://drive.google.com/file/d/1H7cTkuEF2vg7UsiLjnFKJ7kBPIN1Y3IL/view?usp=sharing'
output = 'artifacts/data/SIIM_ISIC_data.zip'
gdown.download(url, output, quiet=False, fuzzy=True)

# extract data

with zipfile.ZipFile(output, 'r') as zip_ref:
    zip_ref.extractall("artifacts/data")
    