#! /bin/bash

# create output folders
mkdir -p artifacts/data/audioset

# download data

curl http://storage.googleapis.com/us_audioset/youtube_corpus/v1/csv/class_labels_indices.csv --output artifacts/data/audioset/class_labels_indices.csv
curl http://storage.googleapis.com/us_audioset/youtube_corpus/v1/csv/eval_segments.csv --output artifacts/data/audioset/eval_segments.csv
curl http://storage.googleapis.com/us_audioset/youtube_corpus/v1/csv/balanced_train_segments.csv --output artifacts/data/audioset/balanced_train_segments.csv
