air_conditioner:
- cassette_air_conditioner
- window_unit
- split_system_air_conditioner
- consumer_durable
- air_conditioners
- cooling_device
- most_cars
- cool_or_warm_the_air
- car_air_conditioner
- externally_powered_device
- cooling_system
- air
- mechanical_device
- air_cooling_device
- control
- electrical_device
- automobile
- enclosed
- air_conditioning
- temperature
- central_air_conditioner
- humidity
- appliance
- machine
- very_important_in_warm_climates
- cool_your_car
- c
car_horn:
- honk
- car
- horn
children_playing:
- playing_tom_tom
- school
- do_string_tricks_with_string
- take_part_in_activities
- tie_their_shoes
- cute
- noisy
- record
- throw_fits
- playings
- class
- parents
- more_tastebuds_than_adults_do
- toys_that_resemle_reptiles_and_amphibians
- more_vulnerable_than_adults
- the_children
- playing_percussion
- bowing
- afraid_of_monsters
- become_adults
- amnesiac_can_forget_that_he
- heavy_users_of_computers
- expect_presents_on_their_birthday
- bad_attitude
- petulant
- catching
- need_care
- playwear
- play_in_back_yard
- playing_cello
- read_stories
- wrong_your_house
- bowling
- sleep_in_beds
- little_people
- kids
- nutmeg
- indirect_victims_of_family_violence
- delight_their_parents
- humans
- toy
- fun
- sons
- count_to_10
- piping
- tie_shoelaces
- be_hanging_laundry
- young
- playing_clarinet
- girls_and_boys
- value_elder's_advise
- use_of_devices
- better_at_video_games_than_adults
- reach_over
- honor_their_parents
- understand_that_their_parents_love_them
- natural_born_actors_and_actresses
- musical_performance
- wash_dishes
- making_music
- some_children
- child
- trade_pokemon_cards
- suffer_abuse
- kitten_playing
- cut_and_paste
- small_people
- use_of_device
- young_people
- trade_cards
- listen_to_the_music
- smaller_heads_than_adults
- younger_than_their_parents
- person
- performing_art
- different_needs_at_different_ages
- most_families_in_the_united_states
- play_games
- card
- many_kids
- pick_up_sticks
- essential_to_growing_up
- shorter_than_adults
- surprise_their_parents
- child_free
- stopping
- bagpiping
- playing_electric_guitar
- paedobaptism
- mother
- play
- tie_their_own_shoes
- immature
- watch_television
- jews
- your_legacy
- taylor_and_triston
- babysat
- kinder
- lots_to_learn
- drink_from_plastic_cups
- call_recording_playback
- recreational_activity
- yips
- married_people
- doll
- golfing
- curious
- innocent
- little
- ball
- no_toys
- learn_the_alphabet
- human
- smaller_than_grown_ups
- bassooning
- trade_baseball_cards
- kick_can
- transposition
- playing_game
- dare_their_friends_to_act
- adults
- try_patience
- devious
- playing_percussion_instrument
- smaller_than_adults
- family
- playing_piano
- enjoy_disney_films
- sweet_natured
- game
- annoying
- play_chess
- physical_event
- greedy
- lymphatism
- recital
- playing_in_bed
- small
- baby_wrangler
- who_needs_tv_when_you
- playing_brass_instrument
- less_dextrous_than_adults
- guitaring
- playing_stringed_instrument
- quality_time
- playing_violin
- real_people
- circuit_bending
- parents_are_people_who
- fun_and_interesting
- immature_homo_sapiens
- learn_that_reading_is_fun
- multiple
- intelligent_agent_activity
- kid
- going_to_school
- people
- movie_showing
- boys
- natural_born_actors
- polyfamily
- camp
- act_out_their_frustrations
- pitching
- you_would_normally_dance_when_music
- borrow_money_from_their_parents
- offspring
- shout_at_each_other
- way_to_learn_social_skills
- playing_saxophone
- girls
- play_leapfrog
- playing_guitar
- your_children
- be_jumping_rope
- play_basketball
- people_and_people_get_things
- play_game
- wonder_why
- information_transfer
- period_of_play
- younger_than_adults
- find_trouble
- impulsive
- action
- taught_spelling_in_school
- share_toys
- playing_gibson_guitar
- prone_to_jumping_in_excitement
- alot_of_fun_at_playgrounds
- thank_parents
- shredding
- count_at_verying_levels
- boys_girls
dog_bark:
- woof
- tree
- tanbark
- canella
- corticiferous
- endophloedal
- snakebark_maple
- hard_covering_for_tree
- cascara
- phellem
- cork
- bay
- winter's_bark
- cassia_bark
- trunk
- peruvian_bark
- dogs
- mezereum
- tapa
- tan
- root
- dog
- wane
- shagbark
- angostura_bark
- animal_noise
- magnolia
- malambo
- noise
- cascarilla_bark
- decorticator
- cinnamon
- wood
- covering
- rough
- paper_birch
- cry
- cascara_sagrada
- living_dog
- ruff
- pau_d_arco
- cinnamon_bark
- branch
- cinchona_bark
- bow_wow
- sailing_vessel
drilling:
- noshore
- bull_wheel
- centerpunch
- drill
- fourble
- refusal
- antidrilling
- drillship
- casing_shoe
- creating_by_removal
- firearm
- barrel
- toolpusher
- underbalanced
- core_sample
- drillings
- derrickman
- postdrilling
engine_idling:
- non_agentive_artifact
- rocket_pack
- auto_tuner
- motor
- continue_to_run
- front_wheel_drive
- automobile_engine
- fanbelt
- dip
- camshaft
- generator
- throttle
- rocket_engine
- train
- spark_plugs_and_oil
- causal_agent
- gearing
- working_well
- oil_change
- the_engine
- decarbonize
- all_trucks
- lawnmower
- mechanical_device
- cars
- catapult
- power_automobile
- auxiliary_engine
- powered_device
- motorcycle
- this_engine
- gas_powered
- car_
- turbofan
- auxiliary
- engine_
- piston
- electric_motor
- external_combustion_engine
- turn_flywheel
- device
- meco
- battering_ram
- power_locomotive
- all_cars
- aircraft_engine
- automobile
- car
- turbine
- heat_engine
- instrument
- oil
- internal_combustion_engine
- diesel_engine
- reaction_propulsion_engine
- go_up_to_5500_rpms
- steam
- equip
- link_motion
gun_shot:
- bullet
- bang
jackhammer:
- jackhammering
- pound
- force
- concrete
- repeatedly
- drill
- matter
- jackhammers
- break
- rock
- form
- kango
- strike
- percussive
- jackhammered
siren:
- lesser_siren
- order
- mermaiden
- aquatic
- sirenidae
- electronic
- acoustic_device
- sirenical
- mechanical
- sea_nymph
- false_alarm
- rusalka
- lure
- fire_alarm_horn
- alarm
- dangerous
- nee_naw
- lorelei
- manatee
- salamander
- wail
- sound_loud
- blue_light
- noise
- device
- usa
- parthenope
- county_seat
- piercingly
- greater_siren
- percussion
- aerophone
street_music:
- hawk
- make_one_happier
- be_settling_to_upset_people
- residential_street
- wagner
- part_music
- named_roadway
- delight_the_senses
- roadway
- record
- overture
- the_street
- mainstream_or_fringe
- lyrics
- cars
- cappella
- avenue
- control_the_populace
- be_two_way_or_one_way
- prelude
- polytonality
- name
- jazz
- stop_sign
- tune
- paved
- irritate
- special_notation
- serialism
- refrain
- relaxing_to_listen_to
- melody
- handel
- melodic_noise
- radio
- dark
- sound
- rhapsody
- ballet
- organized_sounds
- composer
- intonation
- cd
- bring_back_memories
- ta_ziyeh
- pleasure
- environment
- thoroughfare
- bay_street
- make_person_feel_worse
- make_people_feel_many_emotions
- change_your_mood
- quiet_the_mind
- bring_flashbacks
- whitehall
- be_beautifull
- notes
- classical
- metal
- sound_beautiful
- cross_street
- neighbourhood
- one_way_street
- side_street
- brahms
- provide_comfort
- cheers_you_up
- local_road
- stravinsky
- song
- way_to_let_out_emotions
- vocal_music
- neighborhood
- two_way_street
- v344stra_nedsj366v344gen
- make_babbies_happy
- sound_jarring
- information
- cause_you_to_desire_to_dance
- rue
- pleasant_to_listen_to
- chord
- pretty_sound
- music_genre
- sounds
- ludgate_hill
- st
- sound_lovely
- bands
- art
- mews
- haydn
- pizzicato
- road
- vocal_or_instrumental
- monophony
- express_emotion
- distributed_on_albums_(now_cds_)
- city
- drive
- gilbert_and_sullivan
- beats_per_minute
- pavement
- relaxing
- contemporary
- road_avenue
- enjoyable
- lane
- address
- polyphony
- sign
- where_the_cars_ride
- house
- sound_terrible
- be_beutifull
- punishment
- boulevard
- rap
- section
- instruments
- philadelphia
- quiet_the_savage_beast
- universal
- party
- nice_to_listen_to
- bach
- something_you_find_downtown
- recreation
- be_sung_or_played_on_instruments
- driving
- popularism
- album
- auditory_communication
- deliver_emotion
- houses
- classical_music
- harmony
- form
- town
- small
- like
- activity
- heal
- beethoven
- artistic
- main_street
- art_form
- concrete_jungle
- dance
- move_feelings
- instrument
- one_way_or_two_way
- note
- some_music
- express_feelings
- band
- good_for_relaxing_and_dancing
- rhythm
- sound_good
- percussion
- pleasing_to_the_ears
- city_road
- lyrical
- good
- songs
- lead_to_highway
- listening
- tunes
- antiphony
- lift_one's_spirits
- people
- melodic
- main
- bad
- piano_music
- beat
- urban_area
- british_invasion
- spread_happiness
- evoke_emotion
- musical_composition
- be_downloaded_off_of_the_internet
- singing
- be_street
- mozart
- sequence_of_sounds
- soothing
- concert
- opportunity
- chopin
- rock
- composed_and_performed_and_listened_to
- pleasant_to_hear
- alley
- noise
- quiet_babies
- instrumental_music
- effect_on_people
- make_humans_dance
- still_anxiety
- good_or_bad
- entertainment
- roll
- the_sidewalk
- country
- roads
- wake_you_up_in_the_morning
- complex_or_simple
